// Generated by CoffeeScript 1.12.7
module.exports = {
  web: {
    expand: true,
    cwd: 'src/coffee',
    src: ['popup.coffee'],
    dest: 'build/js/',
    ext: '.js'
  },
  web_omega: {
    files: {
      'build/js/omega.js': 'src/omega/**/*.coffee'
    }
  }
};
