// Generated by CoffeeScript 1.12.7
module.exports = {
  grunt: {
    options: {
      reload: true
    },
    files: 'grunt/*',
    tasks: ['default']
  },
  copy_pac: {
    files: 'node_modules/omega-pac/omega_pac.min.js',
    tasks: 'copy:pac'
  },
  copy_img: {
    files: 'img/**/*',
    tasks: 'copy:img'
  },
  copy_popup: {
    files: 'src/popup/**/*',
    tasks: 'copy:popup'
  },
  jade: {
    files: ['src/**/*.jade'],
    tasks: 'jade'
  },
  less: {
    files: 'src/less/**/*.less',
    tasks: ['less', 'autoprefixer']
  },
  scripts: {
    files: ['src/js/**/*.js', 'src/omega/**/*.js'],
    tasks: ['copy:web_scripts', 'concat:web_omega']
  }
};
