"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// @ts-nocheck
// Generated by CoffeeScript 1.12.7
var ContentTypeRejectedError, Promise, Url, defaultHintHandler, fetchUrl, hintHandlers, xhr, xhrWrapper, slice = [].slice;
Promise = OmegaTarget.Promise;
xhr = Promise.promisify(require('xhr'));
Url = require('url');
ContentTypeRejectedError = OmegaTarget.ContentTypeRejectedError;
xhrWrapper = function () {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return xhr.apply(null, args)["catch"](function (err) {
        if (!err.isOperational) {
            throw err;
        }
        if (!err.statusCode) {
            throw new OmegaTarget.NetworkError(err);
        }
        if (err.statusCode === 404) {
            throw new OmegaTarget.HttpNotFoundError(err);
        }
        if (err.statusCode >= 500 && err.statusCode < 600) {
            throw new OmegaTarget.HttpServerError(err);
        }
        throw new OmegaTarget.HttpError(err);
    });
};
fetchUrl = function (dest_url, opt_bypass_cache, opt_type_hints) {
    var dest_url_nocache, getResBody, parsed;
    getResBody = function (arg) {
        var body, contentType, handler, hint, i, len, ref, ref1, response, result;
        response = arg[0], body = arg[1];
        if (!opt_type_hints) {
            return body;
        }
        contentType = (ref = response.headers['content-type']) != null ? ref.toLowerCase() : void 0;
        for (i = 0, len = opt_type_hints.length; i < len; i++) {
            hint = opt_type_hints[i];
            handler = (ref1 = hintHandlers[hint]) != null ? ref1 : defaultHintHandler;
            result = handler(response, body, {
                contentType: contentType,
                hint: hint
            });
            if (result != null) {
                return result;
            }
        }
        throw new ContentTypeRejectedError('Unrecognized Content-Type: ' + contentType);
        return body;
    };
    if (opt_bypass_cache && dest_url.indexOf('?') < 0) {
        parsed = Url.parse(dest_url, true);
        parsed.search = void 0;
        parsed.query['_'] = Date.now();
        dest_url_nocache = Url.format(parsed);
        return xhrWrapper(dest_url_nocache).then(getResBody)["catch"](function () {
            return xhrWrapper(dest_url).then(getResBody);
        });
    }
    else {
        return xhrWrapper(dest_url).then(getResBody);
    }
};
defaultHintHandler = function (response, body, arg) {
    var contentType, hint;
    contentType = arg.contentType, hint = arg.hint;
    if ('!' + contentType === hint) {
        throw new ContentTypeRejectedError('Response Content-Type blacklisted: ' + contentType);
    }
    if (contentType === hint) {
        return body;
    }
};
hintHandlers = {
    '*': function (response, body) {
        return body;
    },
    '!text/html': function (response, body, arg) {
        var contentType, hint, looksLikeHtml;
        contentType = arg.contentType, hint = arg.hint;
        if (contentType === hint) {
            looksLikeHtml = false;
            if (body.indexOf('<!DOCTYPE') >= 0 || body.indexOf('<!doctype') >= 0) {
                looksLikeHtml = true;
            }
            else if (body.indexOf('</html>') >= 0) {
                looksLikeHtml = true;
            }
            else if (body.indexOf('</body>') >= 0) {
                looksLikeHtml = true;
            }
            if (looksLikeHtml) {
                throw new ContentTypeRejectedError('Response must not be HTML.');
            }
        }
    },
    '!application/xhtml+xml': function () {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return hintHandlers['!text/html'].apply(hintHandlers, args);
    },
    'application/x-ns-proxy-autoconfig': function (response, body, arg) {
        var contentType, hint;
        contentType = arg.contentType, hint = arg.hint;
        if (contentType === hint) {
            return body;
        }
        if (body.indexOf('FindProxyForURL') >= 0) {
            return body;
        }
        else {
            return void 0;
        }
    }
};
module.exports = fetchUrl;
