// @ts-nocheck
// Generated by CoffeeScript 1.12.7
var OmegaPac, OmegaTarget,
  hasProp = {}.hasOwnProperty;

OmegaTarget = require('omega-target');

OmegaPac = OmegaTarget.OmegaPac;

module.exports = function(oldOptions, i18n) {
  var Buffer, _, auto, boolItems, color, colorTranslations, conditionFromRule, config, defaultRule, exampleFixedProfileName, haslocalPattern, key, name, nameMap, num, oldKey, oldProfile, oldProfiles, options, profile, protocol, quickSwitch, ref, ref1, rule, rulelist, rules, seenFixedProfile, startupId, text, url;
  config = (function() {
    try {
      return JSON.parse(oldOptions['config']);
    } catch (error) {}
  })();
  if (config) {
    options = typeof changes !== "undefined" && changes !== null ? changes : {};
    options['schemaVersion'] = 2;
    boolItems = {
      '-confirmDeletion': 'confirmDeletion',
      '-refreshOnProfileChange': 'refreshTab',
      '-enableQuickSwitch': 'quickSwitch',
      '-revertProxyChanges': 'preventProxyChanges'
    };
    for (key in boolItems) {
      if (!hasProp.call(boolItems, key)) continue;
      oldKey = boolItems[key];
      options[key] = !!config[oldKey];
    }
    options['-downloadInterval'] = parseInt(config['ruleListReload']) || 15;
    auto = OmegaPac.Profiles.create({
      profileType: 'SwitchProfile',
      name: i18n.upgrade_profile_auto,
      color: '#55bb55',
      defaultProfileName: 'direct'
    });
    OmegaPac.Profiles.updateRevision(auto);
    options[OmegaPac.Profiles.nameAsKey(auto.name)] = auto;
    rulelist = OmegaPac.Profiles.create({
      profileType: 'RuleListProfile',
      name: '__ruleListOf_' + auto.name,
      color: '#dd6633',
      format: config['ruleListAutoProxy'] ? 'AutoProxy' : 'Switchy',
      defaultProfileName: 'direct',
      sourceUrl: config['ruleListUrl'] || ''
    });
    options[OmegaPac.Profiles.nameAsKey(rulelist.name)] = rulelist;
    auto.defaultProfileName = rulelist.name;
    nameMap = {
      'auto': auto.name,
      'direct': 'direct'
    };
    oldProfiles = ((function() {
      try {
        return JSON.parse(oldOptions['profiles']);
      } catch (error) {}
    })()) || {};
    colorTranslations = {
      'blue': '#99ccee',
      'green': '#99dd99',
      'red': '#ffaa88',
      'yellow': '#ffee99',
      'purple': '#d497ee',
      '': '#99ccee'
    };
    seenFixedProfile = false;
    for (_ in oldProfiles) {
      if (!hasProp.call(oldProfiles, _)) continue;
      oldProfile = oldProfiles[_];
      profile = null;
      switch (oldProfile['proxyMode']) {
        case 'auto':
          profile = OmegaPac.Profiles.create({
            profileType: 'PacProfile'
          });
          url = oldProfile['proxyConfigUrl'];
          if (url.substr(0, 5) === 'data:') {
            text = url.substr(url.indexOf(',') + 1);
            Buffer = require('buffer').Buffer;
            text = new Buffer(text, 'base64').toString('utf8');
            profile.pacScript = text;
          } else {
            profile.pacUrl = url;
          }
          break;
        case 'manual':
          seenFixedProfile = true;
          profile = OmegaPac.Profiles.create({
            profileType: 'FixedProfile'
          });
          if (!!oldProfile['useSameProxy']) {
            profile.fallbackProxy = OmegaPac.Profiles.parseHostPort(oldProfile['proxyHttp'], 'http');
          } else if (oldProfile['proxySocks']) {
            protocol = oldProfile['socksVersion'] === 5 ? 'socks5' : 'socks4';
            profile.fallbackProxy = OmegaPac.Profiles.parseHostPort(oldProfile['proxySocks'], protocol);
          } else {
            profile.proxyForHttp = OmegaPac.Profiles.parseHostPort(oldProfile['proxyHttp'], 'http');
            profile.proxyForHttps = OmegaPac.Profiles.parseHostPort(oldProfile['proxyHttps'], 'http');
            profile.proxyForFtp = OmegaPac.Profiles.parseHostPort(oldProfile['proxyFtp'], 'http');
          }
          if (oldProfile['proxyExceptions'] != null) {
            haslocalPattern = false;
            profile.bypassList = [];
            oldProfile['proxyExceptions'].split(';').forEach(function(line) {
              line = line.trim();
              if (!line) {
                return;
              }
              if (line === '<local>') {
                haslocalPattern = true;
              }
              return profile.bypassList.push({
                conditionType: 'BypassCondition',
                pattern: line
              });
            });
            if (haslocalPattern) {
              profile.bypassList = profile.bypassList.filter(function(cond) {
                return OmegaPac.Conditions.localHosts.indexOf(cond.pattern) < 0;
              });
            }
          }
      }
      if (profile) {
        color = oldProfile['color'];
        profile.color = (ref = colorTranslations[color]) != null ? ref : colorTranslations[''];
        name = (ref1 = oldProfile['name']) != null ? ref1 : oldProfile['id'];
        name = name.trim();
        if (name[0] === '_') {
          name = 'p' + name;
        }
        profile.name = name;
        num = 1;
        while (OmegaPac.Profiles.byName(profile.name, options)) {
          profile.name = name + num;
          num++;
        }
        nameMap[oldProfile['id']] = profile.name;
        OmegaPac.Profiles.updateRevision(profile);
        options[OmegaPac.Profiles.nameAsKey(profile.name)] = profile;
      }
    }
    if (!seenFixedProfile) {
      exampleFixedProfileName = 'Example Profile';
      options[OmegaPac.Profiles.nameAsKey(exampleFixedProfileName)] = {
        bypassList: [
          {
            pattern: "127.0.0.1",
            conditionType: "BypassCondition"
          }, {
            pattern: "::1",
            conditionType: "BypassCondition"
          }, {
            pattern: "localhost",
            conditionType: "BypassCondition"
          }
        ],
        profileType: "FixedProfile",
        name: exampleFixedProfileName,
        color: "#99ccee",
        fallbackProxy: {
          port: 8080,
          scheme: "http",
          host: "proxy.example.com"
        }
      };
    }
    startupId = config['startupProfileId'];
    options['-startupProfileName'] = nameMap[startupId] || '';
    quickSwitch = (function() {
      try {
        return JSON.parse(oldOptions['quickSwitchProfiles']);
      } catch (error) {}
    })();
    options['-quickSwitchProfiles'] = quickSwitch == null ? [] : quickSwitch.map(function(p) {
      return nameMap[p];
    });
    if (config['ruleListProfileId']) {
      rulelist.matchProfileName = nameMap[config['ruleListProfileId']] || 'direct';
    }
    defaultRule = (function() {
      try {
        return JSON.parse(oldOptions['defaultRule']);
      } catch (error) {}
    })();
    if (defaultRule) {
      rulelist.defaultProfileName = nameMap[defaultRule.profileId] || 'direct';
      if (!config.ruleListEnabled) {
        auto.defaultProfileName = rulelist.defaultProfileName;
      }
    }
    OmegaPac.Profiles.updateRevision(rulelist);
    rules = (function() {
      try {
        return JSON.parse(oldOptions['rules']);
      } catch (error) {}
    })();
    if (rules) {
      conditionFromRule = function(rule) {
        var pattern;
        switch (rule['patternType']) {
          case 'wildcard':
            pattern = rule['urlPattern'];
            return OmegaPac.RuleList['Switchy'].conditionFromLegacyWildcard(pattern);
          default:
            return {
              conditionType: 'UrlRegexCondition',
              pattern: rule['urlPattern']
            };
        }
      };
      auto.rules = (function() {
        var results;
        results = [];
        for (_ in rules) {
          if (!hasProp.call(rules, _)) continue;
          rule = rules[_];
          results.push({
            profileName: nameMap[rule['profileId']] || 'direct',
            condition: conditionFromRule(rule),
            note: rule.name
          });
        }
        return results;
      })();
    }
    return options;
  }
};

export {};
