importScripts(
  'js/mv3_compat.js',
  'js/log_error.js',
  'js/omega_debug.js',
  'js/background_preload.js',
  'js/omega_pac.min.js',
  'js/omega_target.min.js',
  'js/omega_target_chromium_extension.min.js',
  'img/icons/draw_omega.js',
  'js/background.js'
);
