// Generated by CoffeeScript 1.12.7
var hasProp = {}.hasOwnProperty;

module.exports = function(grunt) {
  var taskDesc;
  taskDesc = 'Convert gettext PO files to Chromium Extension messages format.';
  return grunt.registerMultiTask('po2crx', taskDesc, function() {
    var f, i, j, json, k, key, l, len, len1, matchCount, message, placeholder, placeholders, ref1, ref2, ref3, ref4, refs, result, results, src, value;
    ref1 = this.files;
    results = [];
    for (j = 0, len = ref1.length; j < len; j++) {
      f = ref1[j];
      result = {};
      ref2 = f.src;
      for (k = 0, len1 = ref2.length; k < len1; k++) {
        src = ref2[k];
        json = require('po2json').parseFileSync(src);
        for (key in json) {
          if (!hasProp.call(json, key)) continue;
          value = json[key];
          if (!(key)) {
            continue;
          }
          message = value[1];
          refs = [];
          matchCount = 0;
          message = message.replace(/\$(\d+:)?(\w+)\$/g, function(_, order, ref) {
            matchCount++;
            if (order) {
              order = parseInt(order);
            } else {
              order = matchCount;
            }

            /* TODO(catus): Shall we enable this warning?
            if matchCount > 1
              grunt.log.writeln("In this message: #{key}=#{message}")
              grunt.log.writeln(
                'Order not specified for two or more refs in same message.')
             */
            refs[order] = ref;
            return '$' + ref + '$';
          });
          if (!matchCount) {
            placeholders = void 0;
          } else {
            placeholders = {};
            for (i = l = 0, ref3 = refs.length; 0 <= ref3 ? l < ref3 : l > ref3; i = 0 <= ref3 ? ++l : --l) {
              placeholder = (ref4 = refs[i]) != null ? ref4 : '_unused_' + i;
              placeholders[placeholder] = {
                content: '$' + i
              };
            }
          }
          if (message === ' ') {
            message = '';
          }
          result[key] = {
            message: message,
            placeholders: placeholders
          };
        }
      }
      grunt.file.write(f.dest, JSON.stringify(result));
      results.push(grunt.log.writeln("File \"" + f.dest + "\" created."));
    }
    return results;
  });
};
