// Generated by CoffeeScript 1.12.7
module.exports = function(grunt) {
  require('load-grunt-config')(grunt);
  require('./grunt-po2crx')(grunt);
  return grunt.registerTask('chromium-manifest', function() {
    var manifest;
    manifest = grunt.file.readJSON('overlay/manifest.json');
    manifest.permissions = manifest.permissions.filter(function(p) {
      return p !== 'downloads';
    });
    return grunt.file.write('tmp/manifest.json', JSON.stringify(manifest));
  });
};
