// Generated by CoffeeScript 1.12.7
var path;

path = require('path');

module.exports = {
  index: {
    files: {
      'index.js': 'index.coffee'
    },
    options: {
      transform: ['coffeeify'],
      exclude: ['bluebird', 'omega-pac', 'omega-target'],
      browserifyOptions: {
        extensions: '.coffee',
        builtins: [],
        standalone: 'index.coffee',
        debug: true
      }
    }
  },
  browser: {
    files: {
      'omega_target_chromium_extension.min.js': 'index.coffee'
    },
    options: {
      alias: ['./index.coffee:OmegaTargetChromium'],
      transform: ['coffeeify'],
      plugin: process.env.BUILD === 'release' ? [
        [
          'minifyify', {
            map: false
          }
        ]
      ] : [],
      browserifyOptions: {
        extensions: '.coffee',
        standalone: 'OmegaTargetChromium'
      }
    }
  },
  omega_webext_proxy_script: {
    files: {
      'build/js/omega_webext_proxy_script.min.js': 'src/js/omega_webext_proxy_script.js'
    },
    options: {
      alias: {
        'omega-pac': path.resolve('../omega-pac/omega_pac.min.js')
      },
      plugin: process.env.BUILD === 'release' ? [
        [
          'minifyify', {
            map: false
          }
        ]
      ] : [],
      browserifyOptions: {
        noParse: [path.resolve('../omega-pac/omega_pac.min.js')]
      }
    }
  }
};
