// Generated by CoffeeScript 1.12.7
var BrowserStorage, Promise, Storage,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Storage = require('./storage');

Promise = require('bluebird');

BrowserStorage = (function(superClass) {
  extend(BrowserStorage, superClass);

  function BrowserStorage(storage, prefix) {
    this.storage = storage;
    this.prefix = prefix != null ? prefix : '';
    this.proto = Object.getPrototypeOf(this.storage);
  }

  BrowserStorage.prototype.get = function(keys) {
    var i, key, len, map, value;
    map = {};
    if (typeof keys === 'string') {
      map[keys] = void 0;
    } else if (Array.isArray(keys)) {
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        map[key] = void 0;
      }
    } else if (typeof keys === 'object') {
      map = keys;
    }
    for (key in map) {
      if (!hasProp.call(map, key)) continue;
      try {
        value = JSON.parse(this.proto.getItem.call(this.storage, this.prefix + key));
      } catch (error) {}
      if (value != null) {
        map[key] = value;
      }
      if (typeof map[key] === 'undefined') {
        delete map[key];
      }
    }
    return Promise.resolve(map);
  };

  BrowserStorage.prototype.set = function(items) {
    var key, value;
    for (key in items) {
      if (!hasProp.call(items, key)) continue;
      value = items[key];
      value = JSON.stringify(value);
      this.proto.setItem.call(this.storage, this.prefix + key, value);
    }
    return Promise.resolve(items);
  };

  BrowserStorage.prototype.remove = function(keys) {
    var i, index, key, len;
    if (keys == null) {
      if (!this.prefix) {
        this.proto.clear.call(this.storage);
      } else {
        index = 0;
        while (true) {
          key = this.proto.key.call(index);
          if (key === null) {
            break;
          }
          if (this.key.substr(0, this.prefix.length) === this.prefix) {
            this.proto.removeItem.call(this.storage, this.prefix + keys);
          } else {
            index++;
          }
        }
      }
    }
    if (typeof keys === 'string') {
      this.proto.removeItem.call(this.storage, this.prefix + keys);
    }
    for (i = 0, len = keys.length; i < len; i++) {
      key = keys[i];
      this.proto.removeItem.call(this.storage, this.prefix + key);
    }
    return Promise.resolve();
  };

  return BrowserStorage;

})(Storage);

module.exports = BrowserStorage;
