// Generated by CoffeeScript 1.12.7
var ContentTypeRejectedError, HttpError, HttpNotFoundError, HttpServerError, NetworkError,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

NetworkError = (function(superClass) {
  extend(NetworkError, superClass);

  function NetworkError(err) {
    NetworkError.__super__.constructor.apply(this, arguments);
    this.cause = err;
    this.name = 'NetworkError';
  }

  return NetworkError;

})(Error);

HttpError = (function(superClass) {
  extend(HttpError, superClass);

  function HttpError() {
    var ref;
    HttpError.__super__.constructor.apply(this, arguments);
    this.statusCode = (ref = this.cause) != null ? ref.statusCode : void 0;
    this.name = 'HttpError';
  }

  return HttpError;

})(NetworkError);

HttpNotFoundError = (function(superClass) {
  extend(HttpNotFoundError, superClass);

  function HttpNotFoundError() {
    HttpNotFoundError.__super__.constructor.apply(this, arguments);
    this.name = 'HttpNotFoundError';
  }

  return HttpNotFoundError;

})(HttpError);

HttpServerError = (function(superClass) {
  extend(HttpServerError, superClass);

  function HttpServerError() {
    HttpServerError.__super__.constructor.apply(this, arguments);
    this.name = 'HttpServerError';
  }

  return HttpServerError;

})(HttpError);

ContentTypeRejectedError = (function(superClass) {
  extend(ContentTypeRejectedError, superClass);

  function ContentTypeRejectedError() {
    ContentTypeRejectedError.__super__.constructor.apply(this, arguments);
    this.name = 'ContentTypeRejectedError';
  }

  return ContentTypeRejectedError;

})(Error);

module.exports = {
  NetworkError: NetworkError,
  HttpError: HttpError,
  HttpNotFoundError: HttpNotFoundError,
  HttpServerError: HttpServerError,
  ContentTypeRejectedError: ContentTypeRejectedError
};
