// Generated by CoffeeScript 1.12.7

/* @module omega-target/options_sync */
var Log, OptionsSync, Promise, Revision, Storage, TokenBucket, jsondiffpatch,
  hasProp = {}.hasOwnProperty;

Promise = require('bluebird');

Storage = require('./storage');

Log = require('./log');

Revision = require('omega-pac').Revision;

jsondiffpatch = require('jsondiffpatch');

TokenBucket = require('limiter').TokenBucket;

OptionsSync = (function() {
  OptionsSync.TokenBucket = TokenBucket;

  OptionsSync.prototype._timeout = null;

  OptionsSync.prototype._bucket = null;

  OptionsSync.prototype._waiting = false;


  /**
   * The debounce timeout (ms) for requestPush scheduling. See requestPush.
   * @type number
   */

  OptionsSync.prototype.debounce = 1000;


  /**
   * The throttling timeout (ms) for watchAndPull. See watchAndPull.
   * @type number
   */

  OptionsSync.prototype.pullThrottle = 1000;


  /**
   * The remote storage of syncing.
   * @type Storage
   */

  OptionsSync.prototype.storage = null;

  function OptionsSync(storage, _bucket) {
    var base1;
    this.storage = storage;
    this._bucket = _bucket;
    this._pending = {};
    if (this._bucket == null) {
      this._bucket = new TokenBucket(10, 10, 'minute', null);
    }
    if ((base1 = this._bucket).clear == null) {
      base1.clear = (function(_this) {
        return function() {
          return _this._bucket.tryRemoveTokens(_this._bucket.content);
        };
      })(this);
    }
  }


  /**
   * Transform storage values for syncing. The default implementation applies no
   * transformation, but the behavior can be altered by assigning to this field.
   * Note: Transformation is applied before merging.
   * @param {{}} value The value to transform
   * @param {{}} key The key of the item
   * @returns {{}} The transformed value
   */

  OptionsSync.prototype.transformValue = function(v) {
    return v;
  };


  /**
   * Merge newVal and oldVal of a given key. The default implementation choose
   * between newVal and oldVal based on the following rules:
   * 1. Choose oldVal if syncOptions is 'disabled' in either oldVal or newVal.
   * 2. Choose oldVal if it has a revision newer than or equal to that of newVal.
   * 3. Choose oldVal if it deeply equals newVal.
   * 4. Otherwise, choose newVal.
   *
   * @param {string} key The key of the item
   * @param {} newVal The new value
   * @param {} oldVal The old value
   * @returns {} The merged result
   */

  OptionsSync.prototype.merge = (function() {
    var diff;
    diff = jsondiffpatch.create({
      objectHash: function(obj) {
        return JSON.stringify(obj);
      },
      textDiff: {
        minLength: 1 / 0
      }
    });
    return function(key, newVal, oldVal) {
      var result;
      if (newVal === oldVal) {
        return oldVal;
      }
      if ((oldVal != null ? oldVal.syncOptions : void 0) === 'disabled' || (newVal != null ? newVal.syncOptions : void 0) === 'disabled') {
        return oldVal;
      }
      if (((oldVal != null ? oldVal.revision : void 0) != null) && ((newVal != null ? newVal.revision : void 0) != null)) {
        result = Revision.compare(oldVal.revision, newVal.revision);
        if (result >= 0) {
          return oldVal;
        }
      }
      if (diff.diff(oldVal, newVal) == null) {
        return oldVal;
      }
      return newVal;
    };
  })();


  /**
   * Whether syncing is enabled or not. See requestPush for the effect.
   * @type boolean
   */

  OptionsSync.prototype.enabled = true;


  /**
   * Request pushing the changes to remote storage. The changes are cached first,
   * and then the actual write operations are scheduled if enabled is true.
   * The actual operation is delayed and debounced, combining continuous writes
   * in a short period into a single write operation.
   * @param {Object.<string, {}>} changes A map from keys to values.
   */

  OptionsSync.prototype.requestPush = function(changes) {
    var key, value;
    if (this._timeout != null) {
      clearTimeout(this._timeout);
    }
    for (key in changes) {
      if (!hasProp.call(changes, key)) continue;
      value = changes[key];
      if (typeof value !== 'undefined') {
        value = this.transformValue(value, key);
        if (typeof value === 'undefined') {
          continue;
        }
      }
      this._pending[key] = value;
    }
    if (!this.enabled) {
      return;
    }
    return this._timeout = setTimeout(this._doPush.bind(this), this.debounce);
  };


  /**
   * Returning the pending changes not written to the remote storage.
   * @returns {Object.<string, {}>} The pending changes.
   */

  OptionsSync.prototype.pendingChanges = function() {
    return this._pending;
  };

  OptionsSync.prototype._doPush = function() {
    this._timeout = null;
    if (this._waiting) {
      return;
    }
    this._waiting = true;
    return this._bucket.removeTokens(1, (function(_this) {
      return function() {
        return _this.storage.get(null).then(function(base) {
          var changes;
          changes = _this._pending;
          _this._pending = {};
          _this._waiting = false;
          return Storage.operationsForChanges(changes, {
            base: base,
            merge: _this.merge
          });
        }).then(function(arg) {
          var doSet, remove, set;
          set = arg.set, remove = arg.remove;
          doSet = Object.keys(set).length === 0 ? Promise.resolve(0) : (Log.log('OptionsSync::set', set), _this.storage.set(set)["return"](1));
          return doSet.then(function(cost) {
            set = {};
            if (remove.length > 0) {
              if (_this._bucket.tryRemoveTokens(cost)) {
                Log.log('OptionsSync::remove', remove);
                return _this.storage.remove(remove);
              } else {
                return Promise.reject('bucket');
              }
            }
          })["catch"](function(e) {
            var i, key, len, value, valuesAffected;
            for (key in set) {
              if (!hasProp.call(set, key)) continue;
              value = set[key];
              if (!(key in _this._pending)) {
                _this._pending[key] = value;
              }
            }
            for (i = 0, len = remove.length; i < len; i++) {
              key = remove[i];
              if (!(key in _this._pending)) {
                _this._pending[key] = void 0;
              }
            }
            if (e === 'bucket') {
              return _this._doPush();
            } else if (e instanceof Storage.RateLimitExceededError) {
              Log.log('OptionsSync::rateLimitExceeded');
              _this._bucket.clear();
              _this.requestPush({});
            } else if (e instanceof Storage.QuotaExceededError) {
              valuesAffected = 0;
              for (key in set) {
                if (!hasProp.call(set, key)) continue;
                value = set[key];
                if (key[0] === '+' && value.syncOptions !== 'disabled') {
                  value.syncOptions = 'disabled';
                  value.syncError = {
                    reason: 'quotaPerItem'
                  };
                  valuesAffected++;
                }
              }
              if (valuesAffected > 0) {
                _this.requestPush({});
              } else {
                _this._pending = {};
              }
            } else {
              return Promise.reject(e);
            }
          });
        });
      };
    })(this));
  };

  OptionsSync.prototype._logOperations = function(text, operations) {
    if (Object.keys(operations.set).length) {
      Log.log(text + '::set', operations.set);
    }
    if (operations.remove.length) {
      return Log.log(text + '::remove', operations.remove);
    }
  };


  /**
   * Pull the remote storage for changes, and write them to local.
   * @param {Storage} local The local storage to be written to
   * @returns {function} Calling the returned function will stop watching.
   */

  OptionsSync.prototype.copyTo = function(local) {
    return Promise.join(local.get(null), this.storage.get(null), (function(_this) {
      return function(base, changes) {
        var key, ref;
        for (key in base) {
          if (!hasProp.call(base, key)) continue;
          if (!(key in changes)) {
            if (key[0] === '+' && !((ref = base[key]) != null ? ref.syncOptions : void 0) === 'disabled') {
              changes[key] = void 0;
            }
          }
        }
        return local.apply({
          changes: changes,
          base: base,
          merge: _this.merge
        }).then(function(operations) {
          return _this._logOperations('OptionsSync::copyTo', operations);
        });
      };
    })(this));
  };


  /**
   * Watch the remote storage for changes, and write them to local.
   * The actual writing is throttled by pullThrottle with initial delay.
   * @param {Storage} local The local storage to be written to
   * @returns {function} Calling the returned function will stop watching.
   */

  OptionsSync.prototype.watchAndPull = function(local) {
    var doPull, pull, pullScheduled;
    pullScheduled = null;
    pull = {};
    doPull = (function(_this) {
      return function() {
        return local.get(null).then(function(base) {
          var changes;
          changes = pull;
          pull = {};
          pullScheduled = null;
          return Storage.operationsForChanges(changes, {
            base: base,
            merge: _this.merge
          });
        }).then(function(operations) {
          _this._logOperations('OptionsSync::pull', operations);
          return local.apply(operations);
        });
      };
    })(this);
    return this.storage.watch(null, (function(_this) {
      return function(changes) {
        var key, value;
        for (key in changes) {
          if (!hasProp.call(changes, key)) continue;
          value = changes[key];
          pull[key] = value;
        }
        if (pullScheduled != null) {
          return;
        }
        return pullScheduled = setTimeout(doPull, _this.pullThrottle);
      };
    })(this));
  };

  return OptionsSync;

})();

module.exports = OptionsSync;
