// Generated by CoffeeScript 1.12.7

/* @module omega-target/storage */
var Log, Promise, Storage,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Promise = require('bluebird');

Log = require('./log');

Storage = (function() {
  var QuotaExceededError, RateLimitExceededError, StorageUnavailableError;

  function Storage() {}


  /**
   * Any operation that fails due to rate limiting should reject with an instance
   * of RateLimitExceededError, when implemented in derived classes of Storage.
   */

  Storage.RateLimitExceededError = RateLimitExceededError = (function(superClass) {
    extend(RateLimitExceededError, superClass);

    function RateLimitExceededError() {
      RateLimitExceededError.__super__.constructor.apply(this, arguments);
    }

    return RateLimitExceededError;

  })(Error);


  /**
   * Any operation that fails due to storage quota should reject with an instance
   * of QuotaExceededError, when implemented in derived classes of Storage.
   */

  Storage.QuotaExceededError = QuotaExceededError = (function(superClass) {
    extend(QuotaExceededError, superClass);

    function QuotaExceededError() {
      QuotaExceededError.__super__.constructor.apply(this, arguments);
    }

    return QuotaExceededError;

  })(Error);


  /**
   * If this storage is not available for some reason, all operations should
   * reject with an instance of StorageUnavailableError, when implemented in
   * derived classes of Storage.
   * This error is considered fatal and unrecoverable in the current environment.
   * Further access to this storage should be avoided until restart.
   */

  Storage.StorageUnavailableError = StorageUnavailableError = (function(superClass) {
    extend(StorageUnavailableError, superClass);

    function StorageUnavailableError() {
      StorageUnavailableError.__super__.constructor.apply(this, arguments);
    }

    return StorageUnavailableError;

  })(Error);


  /**
   * A set of operations to be performed on a Storage.
   * @typedef WriteOperations
   * @type {object}
   * @property {Object.<string, {}>} set - A map from keys to new values of the
   * items to set
   * @property {{}[]} remove - An array of keys to remove
   */


  /**
   * Calculate the actual operations against storage that should be performed to
   * replay the changes on a storage.
   * @param {Object.<string, {}>} changes The changes to apply
   * @param {?{}} args Extra arguments
   * @param {Object.<string, {}>?} args.base The original items in the storage.
   * @param {function(key, newVal, oldVal)} args.merge A function that merges
   * the newVal and oldVal. oldVal is provided only if args.base is present.
   * Otherwise it will be equal to newVal (i.e. merge(key, newVal, newVal)).
   * @returns {WriteOperations} The operations that should be performed.
   */

  Storage.operationsForChanges = function(changes, arg) {
    var base, key, merge, newVal, oldVal, ref, remove, set;
    ref = arg != null ? arg : {}, base = ref.base, merge = ref.merge;
    set = {};
    remove = [];
    for (key in changes) {
      newVal = changes[key];
      oldVal = base != null ? base[key] : newVal;
      if (merge) {
        newVal = merge(key, newVal, oldVal);
      }
      if ((base != null) && newVal === oldVal) {
        continue;
      }
      if (typeof newVal === 'undefined') {
        if (typeof oldVal !== 'undefined' || (base == null)) {
          remove.push(key);
        }
      } else {
        set[key] = newVal;
      }
    }
    return {
      set: set,
      remove: remove
    };
  };


  /**
   * Get the requested values by keys from the storage.
   * @param {(string|string[]|null|Object.<string,{}>)} keys The keys to retrive,
   * or null for all.
   * @returns {Promise<(Object.<string, {}>)>} A map from keys to values
   */

  Storage.prototype.get = function(keys) {
    var i, key, len, map, ref, value;
    Log.method('Storage#get', this, arguments);
    if (!this._items) {
      return Promise.resolve({});
    }
    if (keys == null) {
      keys = this._items;
    }
    map = {};
    if (typeof keys === 'string') {
      map[keys] = this._items[keys];
    } else if (Array.isArray(keys)) {
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        map[key] = this._items[key];
      }
    } else if (typeof keys === 'object') {
      for (key in keys) {
        value = keys[key];
        map[key] = (ref = this._items[key]) != null ? ref : value;
      }
    }
    return Promise.resolve(map);
  };


  /**
   * Set multiple values by keys in the storage.
   * @param {(string|Object.<string,{}>)} items A map from key to value to set.
   * @returns {Promise<(Object.<string, {}>)>} A map of key-value pairs just set.
   */

  Storage.prototype.set = function(items) {
    var key, value;
    Log.method('Storage#set', this, arguments);
    if (this._items == null) {
      this._items = {};
    }
    for (key in items) {
      value = items[key];
      this._items[key] = value;
    }
    return Promise.resolve(items);
  };


  /**
   * Remove items by keys from the storage.
   * @param {(string|string[]|null)} keys The keys to remove, or null for all.
   * @returns {Promise} A promise that fulfills on successful removal.
   */

  Storage.prototype.remove = function(keys) {
    var i, key, len;
    Log.method('Storage#remove', this, arguments);
    if (this._items != null) {
      if (keys == null) {
        this._items = {};
      } else if (Array.isArray(keys)) {
        for (i = 0, len = keys.length; i < len; i++) {
          key = keys[i];
          delete this._items[key];
        }
      } else {
        delete this._items[keys];
      }
    }
    return Promise.resolve();
  };


  /**
   * @callback watchCallback
   * @param {Object.<string, {}>} map A map of key-value pairs just changed.
   */


  /**
   * Watch for any changes to the storage.
   * @param {(string|string[]|null)} keys The keys to watch, or null for all.
   * @param {watchCallback} callback Called everytime something changes.
   * @returns {function} Calling the returned function will stop watching.
   */

  Storage.prototype.watch = function(keys, callback) {
    Log.method('Storage#watch', this, arguments);
    return (function() {
      return null;
    });
  };


  /**
   * Apply WriteOperations to the storage.
   * @param {WriteOperations|{changes: Object.<string,{}>}} operations The
   * operations to apply, or the changes to be applied. If changes is provided,
   * the operations are calculated by Storage.operationsForChanges, with extra
   * fields passed through as the second argument.
   * @returns {Promise} A promise that fulfills on operation success.
   */

  Storage.prototype.apply = function(operations) {
    if ('changes' in operations) {
      operations = Storage.operationsForChanges(operations.changes, operations);
    }
    return this.set(operations.set).then((function(_this) {
      return function() {
        return _this.remove(operations.remove);
      };
    })(this))["return"](operations);
  };

  return Storage;

})();

module.exports = Storage;
