// Generated by CoffeeScript 1.12.7
module.exports = {
  index: {
    files: {
      'index.js': 'index.source.js'
    },
    options: {
      exclude: ['uglify-js', 'ip-address'],
      browserifyOptions: {
        builtins: [],
        standalone: 'OmegaPac',
        debug: true
      }
    }
  },
  browser: {
    files: {
      'omega_pac.min.js': './index.source.js'
    },
    options: {
      alias: ['./index.source.js:OmegaPac'],
      plugin: process.env.BUILD === 'release' ? [
        [
          'minifyify', {
            map: false
          }
        ]
      ] : [],
      browserifyOptions: {
        standalone: 'OmegaPac'
      }
    }
  }
};
