// Generated by CoffeeScript 1.12.7
var OmegaTarget, Promise, ProxyAuth, ProxyImpl,
  hasProp = {}.hasOwnProperty;

OmegaTarget = require('omega-target');

Promise = OmegaTarget.Promise;

ProxyAuth = require('./proxy_auth');

ProxyImpl = (function() {
  function ProxyImpl(log) {
    this.log = log;
  }

  ProxyImpl.isSupported = function() {
    return false;
  };

  ProxyImpl.prototype.applyProfile = function(profile, meta) {
    return Promise.reject();
  };

  ProxyImpl.prototype.watchProxyChange = function(callback) {
    return null;
  };

  ProxyImpl.prototype.parseExternalProfile = function(details, options) {
    return null;
  };

  ProxyImpl.prototype._profileNotFound = function(name) {
    this.log.error("Profile " + name + " not found! Things may go very, very wrong.");
    return OmegaPac.Profiles.create({
      name: name,
      profileType: 'VirtualProfile',
      defaultProfileName: 'direct'
    });
  };

  ProxyImpl.prototype.setProxyAuth = function(profile, options) {
    return Promise["try"]((function(_this) {
      return function() {
        var _, name, ref_set, referenced_profiles;
        if (_this._proxyAuth == null) {
          _this._proxyAuth = new ProxyAuth(_this.log);
        }
        _this._proxyAuth.listen();
        referenced_profiles = [];
        ref_set = OmegaPac.Profiles.allReferenceSet(profile, options, {
          profileNotFound: _this._profileNotFound.bind(_this)
        });
        for (_ in ref_set) {
          if (!hasProp.call(ref_set, _)) continue;
          name = ref_set[_];
          profile = OmegaPac.Profiles.byName(name, options);
          if (profile) {
            referenced_profiles.push(profile);
          }
        }
        return _this._proxyAuth.setProxies(referenced_profiles);
      };
    })(this));
  };

  ProxyImpl.prototype.getProfilePacScript = function(profile, meta, options) {
    var ast, prefix, profileName, script;
    if (meta == null) {
      meta = profile;
    }
    ast = OmegaPac.PacGenerator.script(options, profile, {
      profileNotFound: this._profileNotFound.bind(this)
    });
    ast = OmegaPac.PacGenerator.compress(ast);
    script = OmegaPac.PacGenerator.ascii(ast.print_to_string());
    profileName = OmegaPac.PacGenerator.ascii(JSON.stringify(meta.name));
    profileName = profileName.replace(/\*/g, '\\u002a');
    profileName = profileName.replace(/\\/g, '\\u002f');
    prefix = "/*OmegaProfile*" + profileName + "*" + meta.revision + "*/";
    return prefix + script;
  };

  return ProxyImpl;

})();

module.exports = ProxyImpl;
