// Generated by CoffeeScript 1.12.7
var ListenerProxyImpl, NativePromise, OmegaTarget, ProxyImpl,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

OmegaTarget = require('omega-target');

NativePromise = typeof Promise !== "undefined" && Promise !== null ? Promise : null;

ProxyImpl = require('./proxy_impl');

ListenerProxyImpl = (function(superClass) {
  extend(ListenerProxyImpl, superClass);

  ListenerProxyImpl.isSupported = function() {
    var ref;
    return (typeof Promise !== "undefined" && Promise !== null) && ((typeof browser !== "undefined" && browser !== null ? (ref = browser.proxy) != null ? ref.onRequest : void 0 : void 0) != null);
  };

  ListenerProxyImpl.prototype.features = ['fullUrl', 'socks5Auth'];

  function ListenerProxyImpl() {
    ListenerProxyImpl.__super__.constructor.apply(this, arguments);
    this._optionsReady = new NativePromise((function(_this) {
      return function(resolve) {
        return _this._optionsReadyCallback = resolve;
      };
    })(this));
    this._initRequestListeners();
  }

  ListenerProxyImpl.prototype._initRequestListeners = function() {
    browser.proxy.onRequest.addListener(this.onRequest.bind(this), {
      urls: ["<all_urls>"]
    });
    return browser.proxy.onError.addListener(this.onError.bind(this));
  };

  ListenerProxyImpl.prototype.watchProxyChange = function(callback) {
    return null;
  };

  ListenerProxyImpl.prototype.applyProfile = function(profile, state, options) {
    this._options = options;
    this._profile = profile;
    if (typeof this._optionsReadyCallback === "function") {
      this._optionsReadyCallback();
    }
    this._optionsReadyCallback = null;
    return this.setProxyAuth(profile, options);
  };

  ListenerProxyImpl.prototype.onRequest = function(requestDetails) {
    return NativePromise.resolve(this._optionsReady.then((function(_this) {
      return function() {
        var auth, next, profile, proxy, request, result;
        request = OmegaPac.Conditions.requestFromUrl(requestDetails.url);
        profile = _this._profile;
        while (profile) {
          result = OmegaPac.Profiles.match(profile, request);
          if (!result) {
            switch (profile.profileType) {
              case 'DirectProfile':
                return {
                  type: 'direct'
                };
              case 'SystemProfile':
                return void 0;
              default:
                throw new Error('Unsupported profile: ' + profile.profileType);
            }
          }
          if (Array.isArray(result)) {
            proxy = result[2];
            auth = result[3];
            if (proxy) {
              return _this.proxyInfo(proxy, auth);
            }
            next = result[0];
          } else if (result.profileName) {
            next = OmegaPac.Profiles.nameAsKey(result.profileName);
          } else {
            break;
          }
          profile = OmegaPac.Profiles.byKey(next, _this._options);
        }
        throw new Error('Profile not found: ' + next);
      };
    })(this)));
  };

  ListenerProxyImpl.prototype.onError = function(error) {
    return this.log.error(error);
  };

  ListenerProxyImpl.prototype.proxyInfo = function(proxy, auth) {
    var proxyInfo;
    proxyInfo = {
      type: proxy.scheme,
      host: proxy.host,
      port: proxy.port
    };
    if (proxyInfo.type === 'socks5') {
      proxyInfo.type = 'socks';
      if (auth) {
        proxyInfo.username = auth.username;
        proxyInfo.password = auth.password;
      }
    }
    if (proxyInfo.type === 'socks') {
      proxyInfo.proxyDNS = true;
    }
    return [proxyInfo];
  };

  return ListenerProxyImpl;

})(ProxyImpl);

module.exports = ListenerProxyImpl;
