// Generated by CoffeeScript 1.12.7
var OmegaPac, OmegaTarget, Promise, ProxyAuth;

OmegaTarget = require('omega-target');

OmegaPac = OmegaTarget.OmegaPac;

Promise = OmegaTarget.Promise;

module.exports = ProxyAuth = (function() {
  function ProxyAuth(log) {
    this._requests = {};
    this.log = log;
  }

  ProxyAuth.prototype.listening = false;

  ProxyAuth.prototype.listen = function() {
    if (this.listening) {
      return;
    }
    if (!chrome.webRequest) {
      this.log.error('Proxy auth disabled! No webRequest permission.');
      return;
    }
    if (!chrome.webRequest.onAuthRequired) {
      this.log.error('Proxy auth disabled! onAuthRequired not available.');
      return;
    }
    chrome.webRequest.onAuthRequired.addListener(this.authHandler.bind(this), {
      urls: ['<all_urls>']
    }, ['asyncBlocking']);
    chrome.webRequest.onCompleted.addListener(this._requestDone.bind(this), {
      urls: ['<all_urls>']
    });
    chrome.webRequest.onErrorOccurred.addListener(this._requestDone.bind(this), {
      urls: ['<all_urls>']
    });
    return this.listening = true;
  };

  ProxyAuth.prototype._keyForProxy = function(proxy) {
    return (proxy.host.toLowerCase()) + ":" + proxy.port;
  };

  ProxyAuth.prototype.setProxies = function(profiles) {
    var auth, fallback, i, j, key, len, len1, list, profile, proxy, ref, ref1, ref2, results, scheme;
    this._proxies = {};
    this._fallbacks = [];
    results = [];
    for (i = 0, len = profiles.length; i < len; i++) {
      profile = profiles[i];
      if (!profile.auth) {
        continue;
      }
      ref = OmegaPac.Profiles.schemes;
      for (j = 0, len1 = ref.length; j < len1; j++) {
        scheme = ref[j];
        if (!profile[scheme.prop]) {
          continue;
        }
        auth = (ref1 = profile.auth) != null ? ref1[scheme.prop] : void 0;
        if (!auth) {
          continue;
        }
        proxy = profile[scheme.prop];
        key = this._keyForProxy(proxy);
        list = this._proxies[key];
        if (list == null) {
          this._proxies[key] = list = [];
        }
        list.push({
          config: proxy,
          auth: auth,
          name: profile.name + '.' + scheme.prop
        });
      }
      fallback = (ref2 = profile.auth) != null ? ref2['all'] : void 0;
      if (fallback != null) {
        results.push(this._fallbacks.push({
          auth: fallback,
          name: profile.name + '.' + 'all'
        }));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  ProxyAuth.prototype._proxies = {};

  ProxyAuth.prototype._fallbacks = [];

  ProxyAuth.prototype._requests = null;

  ProxyAuth.prototype.authHandler = function(details, callback) {
    var key, list, listLen, proxy, req, respond;
    respond = function(result) {
      if (callback != null) {
        return callback(result);
      } else {
        return result;
      }
    };
    if (!details.isProxy) {
      return respond({});
    }
    req = this._requests[details.requestId];
    if (req == null) {
      this._requests[details.requestId] = req = {
        authTries: 0
      };
    }
    key = this._keyForProxy({
      host: details.challenger.host,
      port: details.challenger.port
    });
    list = this._proxies[key];
    listLen = list != null ? list.length : 0;
    if (req.authTries < listLen) {
      proxy = list[req.authTries];
    } else {
      proxy = this._fallbacks[req.authTries - listLen];
    }
    this.log.log('ProxyAuth', key, req.authTries, proxy != null ? proxy.name : void 0);
    if (proxy == null) {
      return respond({});
    }
    req.authTries++;
    return respond({
      authCredentials: proxy.auth
    });
  };

  ProxyAuth.prototype._requestDone = function(details) {
    return delete this._requests[details.requestId];
  };

  return ProxyAuth;

})();
