// Generated by CoffeeScript 1.12.7
module.exports = function(grunt) {
  var hubAll, hubConfig, i, len, module, submodules;
  submodules = ['omega-pac', 'omega-target', 'omega-web', 'omega-target-*'];
  hubConfig = {
    all: {
      options: {
        concurrent: 2e308
      },
      src: "../*/Gruntfile.*"
    }
  };
  for (i = 0, len = submodules.length; i < len; i++) {
    module = submodules[i];
    hubConfig[module] = {
      src: "../" + module + "/Gruntfile.*"
    };
  }
  hubAll = function(task) {
    var j, len1, results;
    results = [];
    for (j = 0, len1 = submodules.length; j < len1; j++) {
      module = submodules[j];
      results.push("hub:" + module + ":" + task);
    }
    return results;
  };
  grunt.initConfig({
    hub: hubConfig
  });
  grunt.loadNpmTasks('grunt-hub');
  grunt.registerTask('default', hubAll('default'));
  grunt.registerTask('test', hubAll('test'));
  return grunt.registerTask('watch', ['hub:all:watch']);
};
