// Generated by CoffeeScript 1.12.7
module.exports = {
  index: {
    files: {
      'index.js': 'index.coffee'
    },
    options: {
      transform: ['coffeeify'],
      exclude: ['bluebird', 'jsondiffpatch', 'omega-pac'],
      browserifyOptions: {
        extensions: '.coffee',
        builtins: [],
        standalone: 'index.coffee',
        debug: true
      }
    }
  },
  browser: {
    files: {
      'omega_target.min.js': 'index.coffee'
    },
    options: {
      alias: ['./index.coffee:OmegaTarget'],
      transform: ['coffeeify'],
      plugin: process.env.BUILD === 'release' ? [
        [
          'minifyify', {
            map: false
          }
        ]
      ] : [],
      browserifyOptions: {
        extensions: '.coffee',
        standalone: 'OmegaTarget'
      }
    }
  }
};
