// Generated by CoffeeScript 1.12.7
module.exports = {
  grunt: {
    options: {
      reload: true
    },
    files: 'grunt/*',
    tasks: ['default']
  },
  src: {
    files: ['index.source.js', 'src/**/*.js', 'test/**/*.js'],
    tasks: ['default']
  }
};
