// Generated by CoffeeScript 1.12.7
module.exports = {
  grunt: {
    options: {
      reload: true
    },
    files: 'grunt/*',
    tasks: ['default']
  },
  src: {
    files: ['index.coffee', 'src/**/*.js', 'test/**/*.coffee'],
    tasks: ['default']
  }
};
